import type { Metadata } from "next";
import { Bitter, Raleway } from "next/font/google";
import "../globals.css";
import { hasLocale, Locale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Navigation from "@/components/navigation";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const bitter = Bitter({
  variable: "--font-bitter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${raleway.variable} ${bitter.variable} antialiased bg-background`}
      >
        <NextIntlClientProvider>
          <Navigation locale={locale} />
          <main className="">{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
